export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _times = (index: number) =>
  // 'MM/DD/YYYY'
  [
    '11/08/2023',
    '04/09/2024',
    '09/12/2023',
    '01/01/2024',
    '04/23/2024',
    '02/29/2024',
    '05/14/2024',
    '01/13/2024',
    '06/22/2024',
    '10/05/2023',
    '07/11/2024',
    '05/22/2024',
    '03/29/2024',
    '08/29/2023',
    '11/19/2023',
    '10/24/2023',
    '12/02/2023',
    '02/13/2024',
    '09/19/2023',
    '04/17/2024',
    '12/18/2023',
    '06/27/2024',
    '10/19/2023',
    '08/09/2024',
  ][index];

export const _fullName = (index: number) =>
  [
    'Billy Stoltenberg',
    'Eloise Ebert',
    'Teresa Luettgen',
    'Salvador Mayert',
    'Dr. Guadalupe Rath',
    'Kelvin Pouros',
    'Thelma Langworth',
    'Kristen Wunsch',
    'Steve Welch',
    'Brian Jacobs',
    'Lillie Schultz',
    'Mr. Conrad Spinka',
    'Charlene Krajcik',
    'Kerry Kuhlman',
    'Betty Hammes',
    'Tony Paucek PhD',
    'Sherri Davis',
    'Angel Rolfson-Kulas',
    'Dr. Lee Doyle-Grant',
    'Cheryl Romaguera',
    'Billy Braun',
    'Adam Trantow',
    'Brandon Von',
    'Willis Ankunding',
  ][index];

export const _price = (index: number) =>
  [
    35.17, 57.22, 64.78, 50.79, 9.57, 61.46, 96.73, 63.04, 33.18, 36.3, 54.42, 20.52, 62.82, 19.96,
    25.93, 70.39, 23.11, 67.23, 14.31, 31.5, 26.72, 44.8, 37.87, 75.53,
  ][index];

export const _company = (index: number) =>
  [
    'Medhurst, Moore and Franey',
    'Hahn, Homenick and Lind',
    'Larkin LLC',
    'Stamm, Larson and Mertz',
    'Spencer, Raynor and Langosh',
    'Lehner - Feeney',
    'Leuschke, Harris and Kuhlman',
    'Gutmann - Kassulke',
    'Turcotte - Runolfsson',
    'Howe - Anderson',
    'Sipes - Yost',
    'Johns - Aufderhar',
    'Schmidt LLC',
    'Smitham - Gerlach',
    'Waelchi - VonRueden',
    'Padberg - Macejkovic',
    'Lemke - Ferry',
    'Koch and Sons',
    'Klein - Rolfson',
    'Weimann LLC',
    'White, Cassin and Goldner',
    'Mohr, Langworth and Hills',
    'Mitchell, Volkman and Prosacco',
    'Streich Group',
  ][index];

export const _boolean = (index: number) =>
  [
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
  ][index];

export const _postTitles = (index: number) =>
  [
    'Whiteboard Templates By Industry Leaders',
    'Tesla Cybertruck-inspired camper trailer for Tesla fans who can’t just wait for the truck!',
    'Designify Agency Landing Page Design',
    '✨What is Done is Done ✨',
    'Fresh Prince',
    'Six Socks Studio',
    'vincenzo de cotiis’ crossing over showcases a research on contamination',
    'Simple, Great Looking Animations in Your Project | Video Tutorial',
    '40 Free Serif Fonts for Digital Designers',
    'Examining the Evolution of the Typical Web Design Client',
    'Katie Griffin loves making that homey art',
    'The American Dream retold through mid-century railroad graphics',
    'Illustration System Design',
    'CarZio-Delivery Driver App SignIn/SignUp',
    'How to create a client-serverless Jamstack app using Netlify, Gatsby and Fauna',
    'Tylko Organise effortlessly -3D & Motion Design',
    'RAYO ?? A expanded visual arts festival identity',
    'Anthony Burrill and Wired mag’s Andrew Diprose discuss how they made January’s Change Everything cover',
    'Inside the Mind of Samuel Day',
    'Portfolio Review: Is This Portfolio Too Creative?',
    'Akkers van Margraten',
    'Gradient Ticket icon',
    'Here’s a Dyson motorcycle concept that doesn’t ‘suck’!',
    'How to Animate a SVG with border-image',
  ][index];

export const _description = (index: number) =>
  [
    'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    'The Football Is Good For Training And Recreational Purposes',
    'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    'The Football Is Good For Training And Recreational Purposes',
    'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
  ][index];

export const _taskNames = (index: number) =>
  [
    `Prepare Monthly Financial Report`,
    `Design New Marketing Campaign`,
    `Analyze Customer Feedback`,
  ][index];

export const _vocabulary = (index: number) =>
  [
    '나라 Quốc Gia',
    '직업 Nghề nghiệp',
    '인사말 Lời chào',
    '장소 Nơi chốn',
    '학교 시설 Trang thiết bị trường học',
    '교실 물건 Đồ vật trong phòng học'
  ][index];


export const _topic_vocab_list = [
  {
    id: 'country',
    kr: '나라',
    vi: 'Quốc gia',
    vocabulary: [
      { kr: '한국', vi: 'Hàn Quốc' },
      { kr: '베트남', vi: 'Việt Nam' },
      { kr: '일본', vi: 'Nhật Bản' },
      { kr: '중국', vi: 'Trung Quốc' },
    ],
  },
  {
    id: 'job',
    kr: '직업',
    vi: 'Nghề nghiệp',
    vocabulary: [
      { kr: '학생', vi: 'Học sinh' },
      { kr: '회사원', vi: 'Nhân viên công ty' },
      { kr: '은행원', vi: 'Nhân viên ngân hàng' },
      { kr: '선생님', vi: 'Giáo viên' },
      { kr: '의사', vi: 'Bác sĩ' },
      { kr: '공무원', vi: 'Công chức' },
      { kr: '관광 가이드', vi: 'Hướng dẫn viên du lịch' },
      { kr: '주부', vi: 'Nội trợ' },
      { kr: '약사', vi: 'Dược sĩ' },
      { kr: '운전기사', vi: 'Tài xế lái xe' },
    ],
  },
    {
    id: 'greeting',
    kr: '인사말',
    vi: 'Lời chào',
    vocabulary: [
      { kr: '안녕하세요?', vi: 'Xin chào?' },
      { kr: '안녕하십니까?', vi: 'Xin chào? (trịnh trọng)' },
      { kr: '안녕히 가세요', vi: 'Xin tạm biệt (Đi về bình an)' },
      { kr: '안녕히 계세요', vi: 'Xin tạm biệt (Ở lại bình an)' },
      { kr: '처음 뵙겠습니다', vi: 'Rất hân hạnh. (Lần đầu gặp mặt)' },
      { kr: '반갑습니다', vi: 'Rất vui được gặp' },
    ],
  },
  {
  id: 'place',
  kr: '장소',
  vi: 'Nơi chốn',
  vocabulary: [
    { kr: '학교', vi: 'Trường học' },
    { kr: '도서관', vi: 'Thư viện' },
    { kr: '식당', vi: 'Nhà ăn, nhà hàng' },
    { kr: '호텔', vi: 'Khách sạn' },
    { kr: '극장', vi: 'Nhà hát' },
    { kr: '우체국', vi: 'Bưu điện' },
    { kr: '병원', vi: 'Bệnh viện' },
    { kr: '은행', vi: 'Ngân hàng' },
    { kr: '백화점', vi: 'Cửa hàng bách hoá' },
    { kr: '약국', vi: 'Hiệu thuốc' },
    { kr: '가게', vi: 'Cửa tiệm, cửa hàng' },
    { kr: '사무실', vi: 'Văn phòng' },
  ],
  },
  {
  id: 'school-equipment',
  kr: '학교 시설',
  vi: 'Trang thiết bị trường học',
  vocabulary: [
    { kr: '강의실', vi: 'Giảng đường' },
    { kr: '교실', vi: 'Phòng học' },
    { kr: '화장실', vi: 'Nhà vệ sinh' },
    { kr: '휴게실', vi: 'Phòng nghỉ' },
    { kr: '랩실(어학실)', vi: 'Phòng lab' },
    { kr: '동아리방', vi: 'Phòng sinh hoạt câu lạc bộ' },
    { kr: '체육관', vi: 'Nhà thi đấu thể thao' },
    { kr: '운동장', vi: 'Sân vận động' },
    { kr: '강당', vi: 'Giảng đường lớn, hội trường' },
    { kr: '학생 식당', vi: 'Nhà ăn học sinh' },
    { kr: '세미나실', vi: 'Phòng hội thảo' },
    { kr: '서점', vi: 'Hiệu sách' },
  ],
  },
    {
    id: 'classroom-items',
    kr: '교실 물건',
    vi: 'Đồ vật trong phòng học',
    vocabulary: [
      { kr: '책상', vi: 'Bàn' },
      { kr: '의자', vi: 'Cái ghế' },
      { kr: '칠판', vi: 'Bảng' },
      { kr: '문', vi: 'Cửa' },
      { kr: '창문', vi: 'Cửa sổ' },
      { kr: '시계', vi: 'Đồng hồ' },
      { kr: '가방', vi: 'Cặp sách' },
      { kr: '컴퓨터', vi: 'Máy vi tính' },
      { kr: '책', vi: 'Sách' },
      { kr: '공책', vi: 'Vở' },
      { kr: '사전', vi: 'Từ điển' },
      { kr: '지우개', vi: 'Cục tẩy' },
      { kr: '지도', vi: 'Bản đồ' },
      { kr: '펜', vi: 'Bút, viết' },
      { kr: '필통', vi: 'Hộp bút' },
    ],
  },
  {
    id: 'verb',
    kr: '동서',
    vi: 'Động từ',
    vocabulary: [
        { kr: '가다', vi: 'Đi' },
        { kr: '오다', vi: 'Đến' },
        { kr: '자다', vi: 'Ngủ' },
        { kr: '먹다', vi: 'Ăn' },
        { kr: '마시다', vi: 'Uống' },
        { kr: '이야기하다', vi: 'Nói chuyện' },
        { kr: '읽다', vi: 'Đọc' },
        { kr: '듣다', vi: 'Nghe' },
        { kr: '보다', vi: 'Nhìn, xem' },
        { kr: '일하다', vi: 'Làm việc' },
        { kr: '공부하다', vi: 'Học' },
        { kr: '운동하다', vi: 'Luyện tập thể thao, vận động' },
        { kr: '쉬다', vi: 'Nghỉ, nghỉ ngơi' },
        { kr: '만나다', vi: 'Gặp gỡ' },
        { kr: '사다', vi: 'Mua' },
        { kr: '좋아하다', vi: 'Thích' },
    ],
  },
  {
  id: 'adjectives',
  kr: '형용사',
  vi: 'Tính từ',
  vocabulary: [
    { kr: '크다', vi: 'To, lớn' },
    { kr: '작다', vi: 'Nhỏ' },
    { kr: '많다', vi: 'Nhiều' },
    { kr: '적다', vi: 'Ít' },
    { kr: '좋다', vi: 'Tốt' },
    { kr: '나쁘다', vi: 'Xấu, tồi' },
    { kr: '재미있다', vi: 'Hay, thú vị' },
    { kr: '재미없다', vi: 'Không hay' },
  ],
  },
  {
    id: 'weekday',
    kr: '요일',
    vi: 'Thứ',
    vocabulary: [
      { kr: '월요일', vi: 'Thứ hai' },
      { kr: '화요일', vi: 'Thứ ba' },
      { kr: '수요일', vi: 'Thứ tư' },
      { kr: '목요일', vi: 'Thứ năm' },
      { kr: '금요일', vi: 'Thứ sáu' },
      { kr: '토요일', vi: 'Thứ bảy' },
      { kr: '일요일', vi: 'Chủ nhật' },
    ],
  },
  {
    id: 'time_period',
    kr: '시간 표현',
    vi: 'Thời gian',
    vocabulary: [
      { kr: '그저께', vi: 'Hôm kia' },
      { kr: '어제', vi: 'Hôm qua' },
      { kr: '오늘', vi: 'Hôm nay' },
      { kr: '내일', vi: 'Ngày mai' },
      { kr: '모레', vi: 'Ngày kia' },
      { kr: '지난해', vi: 'Năm ngoái (지)' },
      { kr: '작년', vi: 'Năm ngoái (작)' },
      { kr: '올해', vi: 'Năm nay (ᄋ)' },
      { kr: '금년', vi: 'Năm nay (ᄀ)' },
      { kr: '다음 해', vi: 'Năm sau (ᄃ)' },
      { kr: '내년', vi: 'Năm sau (ᄂ)' },
      { kr: '지난달', vi: 'Tháng trước' },
      { kr: '이번 달', vi: 'Tháng này' },
      { kr: '다음 달', vi: 'Tháng sau' },
      { kr: '지난주', vi: 'Tuần trước' },
      { kr: '이번 주', vi: 'Tuần này' },
      { kr: '다음 주', vi: 'Tuần sau' },
      { kr: '평일', vi: 'Ngày thường trong tuần (ᄑ)' },
      { kr: '주중', vi: 'Ngày thường trong tuần (ᄌ)' },
      { kr: '주말', vi: 'Cuối tuần' },
    ],
  },
  {
    id: 'month',
    kr: '월',
    vi: 'Tháng',
    vocabulary: [
      { kr: '1월', vi: 'Tháng 1' },
      { kr: '2월', vi: 'Tháng 2' },
      { kr: '3월', vi: 'Tháng 3' },
      { kr: '4월', vi: 'Tháng 4' },
      { kr: '5월', vi: 'Tháng 5' },
      { kr: '6월', vi: 'Tháng 6' },
      { kr: '7월', vi: 'Tháng 7' },
      { kr: '8월', vi: 'Tháng 8' },
      { kr: '9월', vi: 'Tháng 9' },
      { kr: '10월', vi: 'Tháng 10' },
      { kr: '11월', vi: 'Tháng 11' },
      { kr: '12월', vi: 'Tháng 12' },
    ],
  },
  {
  id: 'time',
  kr: '시간',
  vi: 'Thời gian',
  vocabulary: [
    { kr: '오전', vi: 'Buổi sáng' },
    { kr: '오후', vi: 'Buổi chiều' },
    { kr: '낮', vi: 'Ban ngày' },
    { kr: '밤', vi: 'Ban đêm' },  
    { kr: '아침', vi: 'Sáng' },
    { kr: '점심', vi: 'Trưa' },
    { kr: '저녁', vi: 'Tối' },
    { kr: '새벽', vi: 'Sáng sớm' },
  ],
  },
  {
  id: 'daily-verbs',
  kr: '일상표현동사',
  vi: 'Động từ chỉ hoạt động hàng ngày',
  vocabulary: [
    { kr: '일어나다', vi: 'Thức dậy' },
    { kr: '이를 닦다', vi: 'Đánh răng' },
    { kr: '세수하다', vi: 'Rửa mặt' },
    { kr: '읽다', vi: 'Đọc' },
    { kr: '보다', vi: 'Nhìn, xem' },
    { kr: '다니다', vi: 'Đi lại (có tính thường xuyên)' },
    { kr: '배우다', vi: 'Học' },
    { kr: '숙제하다', vi: 'Làm bài tập' },
    { kr: '청소하다', vi: 'Dọn vệ sinh' },
    { kr: '목욕하다', vi: 'Tắm' },
    { kr: '출근하다', vi: 'Đi làm' },
    { kr: '퇴근하다', vi: 'Tan tầm' },
    { kr: '시작하다', vi: 'Bắt đầu' },
    { kr: '끝나다', vi: 'Xong, kết thúc' },
    { kr: '자다', vi: 'Ngủ' },
  ],
}
];

export const _number_list = [
  {
    id: 'sino_korean_number',
    kr: '한자어 수',
    vi: 'Hán Hàn',
    vocabulary: [
      { kr: '일', vi: '1' },
      { kr: '이', vi: '2' },
      { kr: '삼', vi: '3' },
      { kr: '사', vi: '4' },
      { kr: '오', vi: '5' },
      { kr: '육', vi: '6' },
      { kr: '칠', vi: '7' },
      { kr: '팔', vi: '8' },
      { kr: '구', vi: '9' },
      { kr: '십', vi: '10' },
    ],
  },
  {
    id: 'native_korean_number',
    kr: '고유어 수',
    vi: 'Thuần Hàn',
    vocabulary: [
      { kr: '하나', vi: '1' },
      { kr: '둘', vi: '2' },
      { kr: '셋', vi: '3' },
      { kr: '넷', vi: '4' },
      { kr: '다섯', vi: '5' },
      { kr: '여섯', vi: '6' },
      { kr: '일곱', vi: '7' },
      { kr: '여덟', vi: '8' },
      { kr: '아홉', vi: '9' },
      { kr: '열', vi: '10' },
    ],
  },
];
